"""
Builds notebooks/telemetry_analysis.ipynb.


"""

import json
import os

CELLS = [
    ("markdown", """# Formula SAE Telemetry Analyzer

Exploratory analysis of synthetic Formula SAE-style telemetry.

**All data here is synthetic.** It is generated by `src/generate_telemetry.py`
and does not come from any real vehicle or team. Two sessions carry
deliberately injected faults so the vehicle-health checks can be validated
against a known answer: S04 has degraded cooling, S06 has a weak battery cell.

This notebook explores the data visually. The analysis logic lives in `src/`;
nothing is reimplemented here."""),

    ("code", """import sys
sys.path.append("..")

import matplotlib.pyplot as plt
import pandas as pd

from src.analysis import consistency_metrics, health_report
from src.database import run_query
from src.lap_comparison import compare_laps
from src.run_sql import run_named_query

plt.rcParams["figure.figsize"] = (11, 4.5)
plt.rcParams["axes.grid"] = True
plt.rcParams["grid.alpha"] = 0.3

print("Loaded.")"""),

    ("markdown", """## 1. Session overview

Six sessions, eight laps each. The sessions differ in ambient temperature,
driver aggression, and driver consistency."""),

    ("code", """sessions = run_named_query("session_summary")
sessions[["session_id", "label", "ambient_temp_c", "driver_aggression",
          "best_lap_s", "avg_lap_s", "top_speed_kmh"]]"""),

    ("markdown", """## 2. Lap time distribution

Each session's laps, with the out-lap included. Lap 1 always starts from a
standstill, which is why it sits clear of the rest in every session."""),

    ("code", """laps = run_query("SELECT session_id, lap_number, lap_time_s FROM laps")

fig, ax = plt.subplots()
for session_id, group in laps.groupby("session_id"):
    ax.plot(group["lap_number"], group["lap_time_s"], marker="o", label=session_id)

ax.set_xlabel("Lap number")
ax.set_ylabel("Lap time (s)")
ax.set_title("Lap times by session")
ax.legend(ncol=6, fontsize=9)
plt.tight_layout()"""),

    ("markdown", """The spread within each session is what the consistency metric measures.
Standard deviation is taken with the out-lap excluded, since a standing start
would otherwise dominate it."""),

    ("code", """consistency = consistency_metrics()

fig, ax = plt.subplots(figsize=(7, 4))
ax.barh(consistency["session_id"], consistency["std_dev_s"], color="#4a7ba7")
ax.set_xlabel("Lap time standard deviation (s)")
ax.set_title("Consistency by session (out-lap excluded)")
ax.invert_yaxis()
plt.tight_layout()

consistency"""),

    ("markdown", """## 3. Speed over distance

One lap of the baseline session. The track's eight sections are shaded so the
speed trace can be read against the layout: the car is quickest on the Long
Straight and slowest through the Hairpin."""),

    ("code", """from src.track import TRACK_SECTIONS

lap = run_query(
    "SELECT distance_m, speed_kmh, throttle_pct, brake_pressure_pct, rpm "
    "FROM telemetry WHERE session_id = 'S02' AND lap_number = 3 "
    "ORDER BY distance_m"
)

fig, ax = plt.subplots()

for i, section in enumerate(TRACK_SECTIONS):
    ax.axvspan(section["start_m"], section["end_m"],
               alpha=0.08, color="grey" if i % 2 else "white")
    ax.text((section["start_m"] + section["end_m"]) / 2, 8,
            section["name"], rotation=90, fontsize=7,
            ha="center", va="bottom", alpha=0.6)

ax.plot(lap["distance_m"], lap["speed_kmh"], color="#c0392b", linewidth=1.5)
ax.set_xlabel("Distance (m)")
ax.set_ylabel("Speed (km/h)")
ax.set_title("Speed over distance — S02 lap 3")
ax.set_ylim(0, 125)
plt.tight_layout()"""),

    ("markdown", """## 4. Driver inputs

Throttle and brake over the same lap. Braking happens at the *end* of straights,
before the corner — not in it. That is the lookahead in the driver model
working: it scans ahead, sees a slower section coming, and lifts early."""),

    ("code", """fig, (ax_t, ax_b) = plt.subplots(2, 1, figsize=(11, 5), sharex=True)

ax_t.plot(lap["distance_m"], lap["throttle_pct"],
          color="#27ae60", linewidth=1.2)
ax_t.fill_between(lap["distance_m"], 0, lap["throttle_pct"],
                  color="#27ae60", alpha=0.25)
ax_t.set_ylabel("Throttle (%)")
ax_t.set_ylim(0, 105)
ax_t.set_title("Driver inputs over distance — S02 lap 3")

ax_b.plot(lap["distance_m"], lap["brake_pressure_pct"],
          color="#c0392b", linewidth=1.2)
ax_b.fill_between(lap["distance_m"], 0, lap["brake_pressure_pct"],
                  color="#c0392b", alpha=0.25)
ax_b.set_ylabel("Brake (%)")
ax_b.set_ylim(0, 105)
ax_b.set_xlabel("Distance (m)")

plt.tight_layout()"""),

    ("markdown", """## 5. Lap comparison

The fastest and slowest laps of the baseline session, aligned onto a common
distance grid. Two laps have different sample counts because they took
different amounts of time, so they cannot be compared sample by sample —
both are interpolated onto the same distance axis first.

The lower panel is the cumulative time delta. Where it rises, the slower lap
is losing time; where it is flat, the two laps are even."""),

    ("code", """best_worst = run_query(
    "SELECT lap_number, lap_time_s FROM laps "
    "WHERE session_id = 'S02' AND lap_number > 1 ORDER BY lap_time_s"
)
fast = int(best_worst.iloc[0]["lap_number"])
slow = int(best_worst.iloc[-1]["lap_number"])

comp = compare_laps("S02", fast, "S02", slow)

fig, (ax1, ax2) = plt.subplots(2, 1, figsize=(11, 7), sharex=True)

ax1.plot(comp["distance_m"], comp["speed_a_kmh"],
         label=f"Lap {fast} (faster)", color="#27ae60", linewidth=1.4)
ax1.plot(comp["distance_m"], comp["speed_b_kmh"],
         label=f"Lap {slow} (slower)", color="#c0392b", linewidth=1.4)
ax1.set_ylabel("Speed (km/h)")
ax1.set_title(f"S02 lap {fast} versus lap {slow}")
ax1.legend()

ax2.fill_between(comp["distance_m"], 0, comp["time_delta_s"],
                 color="#4a7ba7", alpha=0.6)
ax2.axhline(0, color="black", linewidth=0.8)
ax2.set_xlabel("Distance (m)")
ax2.set_ylabel("Cumulative delta (s)")
ax2.set_title("Time lost by the slower lap")

plt.tight_layout()

print(f"Final delta: {comp['time_delta_s'].iloc[-1]:+.3f} s")"""),

    ("markdown", """## 6. Temperature across a session

Powertrain temperature over the whole of each session. A healthy car heats up
early and then levels off as cooling catches up with heat production. S04 does
not level off, which is the seeded cooling fault."""),

    ("code", """temps = run_query(
    "SELECT session_id, session_time_s, powertrain_temp_c FROM telemetry "
    "ORDER BY session_id, session_time_s"
)

fig, ax = plt.subplots()
for session_id, group in temps.groupby("session_id"):
    thinned = group.iloc[::20]
    ax.plot(thinned["session_time_s"], thinned["powertrain_temp_c"],
            label=session_id, linewidth=1.2)

ax.axhline(95, color="orange", linestyle="--", linewidth=1,
           label="Elevated threshold")
ax.axhline(110, color="red", linestyle="--", linewidth=1,
           label="High threshold")
ax.set_xlabel("Session time (s)")
ax.set_ylabel("Powertrain temperature (C)")
ax.set_title("Temperature across each session")
ax.legend(ncol=4, fontsize=8)
plt.tight_layout()"""),

    ("markdown", """Absolute temperature alone would partly conflate a hot day with a cooling
problem. Temperature *rise over ambient* separates them: S03 ran on the hottest
day in the set and still shows one of the smaller rises."""),

    ("code", """health = health_report()

fig, ax = plt.subplots(figsize=(7, 4))
colours = ["#c0392b" if s != "OK" else "#4a7ba7"
           for s in health["overall_status"]]
ax.barh(health["session_id"], health["temp_rise_over_ambient_c"], color=colours)
ax.set_xlabel("Temperature rise over ambient (C)")
ax.set_title("Thermal load by session (flagged sessions in red)")
ax.invert_yaxis()
plt.tight_layout()

health[["session_id", "ambient_temp_c", "peak_temp_c",
        "temp_rise_over_ambient_c", "seeded_fault", "overall_status"]]"""),

    ("markdown", """## 7. Voltage under load

Pack voltage sags under load because of internal resistance and recovers when
the load comes off. Comparing loaded against unloaded voltage *within* a session
controls for state of charge, so what is left is the pack's internal resistance.

S06 sags roughly twice as hard as the rest, which is the seeded weak cell."""),

    ("code", """sag = run_named_query("voltage_sag_under_load")

fig, ax = plt.subplots(figsize=(7, 4))
colours = ["#c0392b" if f == "battery" else "#4a7ba7"
           for f in sag["seeded_fault"].fillna("")]
ax.barh(sag["session_id"], sag["sag_v"], color=colours)
ax.set_xlabel("Voltage sag under load (V)")
ax.set_title("Pack voltage sag (weak-cell session in red)")
ax.invert_yaxis()
plt.tight_layout()

sag"""),

    ("markdown", """## Notes and limitations

- Lap time is **counted** from simulation timesteps, never generated. A faster
  lap covers more distance per step and so needs fewer steps.
- The distance-aligned comparison reconciles with the lap-time table exactly,
  which is what shows the interpolation is correct.
- **Theoretical best lap** (sum of each session's best sector times) sits within
  ±0.2 s of the actual best lap for every session. Sector times are
  reconstructed from 10 Hz samples and so carry about 0.1 s of quantisation
  each, and the simulated driver's sector-to-sector variation happens to be a
  similar size. The query is correct; the simulation does not produce enough
  sector-level variation for the metric to measure.
- The simulation is a simplified point-mass model, not a vehicle-dynamics
  simulator. The numbers are chosen to be plausible and internally consistent,
  not accurate."""),
]


def build():
    cells = []
    for cell_type, source in CELLS:
        # Jupyter stores source as a list of lines, each ending in a
        # newline except the last
        lines = source.split("\n")
        source_lines = [line + "\n" for line in lines[:-1]] + [lines[-1]]

        cell = {
            "cell_type": cell_type,
            "metadata": {},
            "source": source_lines,
        }
        if cell_type == "code":
            cell["execution_count"] = None
            cell["outputs"] = []
        cells.append(cell)

    notebook = {
        "cells": cells,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.12"},
        },
        "nbformat": 4,
        "nbformat_minor": 5,
    }

    path = os.path.join(os.path.dirname(__file__), "telemetry_analysis.ipynb")
    with open(path, "w") as f:
        json.dump(notebook, f, indent=1)

    print(f"Wrote {path} with {len(cells)} cells.")


if __name__ == "__main__":
    build()