"""
SQLite database creation and loading.

Builds the schema from sql/schema.sql and loads the processed CSVs into it.
The database is a build artifact -- it is gitignored and regenerated by
running this module, so it never goes stale relative to the data.

Session metadata comes from the generator's SESSION_PROFILES rather than
from the CSVs, because the profile is what the session was generated under
and is not recoverable from the telemetry alone.
"""

import os
import sqlite3

import pandas as pd

from src.generate_telemetry import LAPS_PER_SESSION, SESSION_PROFILES

DB_PATH = "data/telemetry.db"
SCHEMA_PATH = "sql/schema.sql"

CLEAN_PATH = "data/processed/clean_telemetry.csv"
LAP_SUMMARY_PATH = "data/processed/lap_summary.csv"
SECTOR_SUMMARY_PATH = "data/processed/sector_summary.csv"


def connect(db_path=DB_PATH):
    """Open a connection with foreign key enforcement switched on.

    SQLite does not enforce foreign keys unless asked, which surprises
    people. Without this pragma the FOREIGN KEY lines in the schema are
    documentation rather than constraints.
    """
    conn = sqlite3.connect(db_path)
    conn.execute("PRAGMA foreign_keys = ON")
    return conn


def create_schema(conn, schema_path=SCHEMA_PATH):
    """Run the schema file, dropping and recreating every table."""
    with open(schema_path, "r") as f:
        schema_sql = f.read()
    conn.executescript(schema_sql)
    conn.commit()


def load_sessions(conn):
    """Insert one row per session from the generator's profiles."""
    rows = [
        (
            profile["session_id"],
            profile["label"],
            profile["ambient_c"],
            profile["aggression"],
            profile["consistency"],
            profile["fault"],
            LAPS_PER_SESSION,
        )
        for profile in SESSION_PROFILES
    ]

    conn.executemany(
        """
        INSERT INTO sessions (
            session_id, label, ambient_temp_c, driver_aggression,
            driver_consistency, seeded_fault, lap_count
        ) VALUES (?, ?, ?, ?, ?, ?, ?)
        """,
        rows,
    )
    conn.commit()
    return len(rows)


def load_table_from_csv(conn, csv_path, table_name, columns):
    """Load a CSV into a table, inserting only the named columns.

    Pandas' to_sql would be shorter, but it bypasses the table definition
    and would silently create its own. Writing the INSERT explicitly means
    the CHECK constraints and foreign keys actually apply.
    """
    df = pd.read_csv(csv_path)
    df = df[columns]

    placeholders = ", ".join("?" for _ in columns)
    column_list = ", ".join(columns)
    sql = f"INSERT INTO {table_name} ({column_list}) VALUES ({placeholders})"

    conn.executemany(sql, df.itertuples(index=False, name=None))
    conn.commit()
    return len(df)


def build_database(db_path=DB_PATH, verbose=True):
    """Create the database from scratch and load every table."""
    # Remove any previous build so the load always starts clean.
    if os.path.exists(db_path):
        os.remove(db_path)

    conn = connect(db_path)

    create_schema(conn)
    if verbose:
        print(f"Created schema from {SCHEMA_PATH}")

    session_count = load_sessions(conn)
    if verbose:
        print(f"  sessions   {session_count:>7,} rows")

    lap_count = load_table_from_csv(
        conn,
        LAP_SUMMARY_PATH,
        "laps",
        [
            "session_id", "lap_number", "lap_time_s", "sample_count",
            "avg_speed_kmh", "max_speed_kmh", "min_speed_kmh", "peak_rpm",
            "avg_throttle_pct", "full_throttle_pct", "peak_brake_pct",
            "braking_events", "peak_temp_c", "avg_temp_c", "min_voltage_v",
            "max_abs_steering_deg",
        ],
    )
    if verbose:
        print(f"  laps       {lap_count:>7,} rows")

    sector_count = load_table_from_csv(
        conn,
        SECTOR_SUMMARY_PATH,
        "sectors",
        [
            "session_id", "lap_number", "sector", "sector_time_s",
            "avg_speed_kmh", "min_speed_kmh", "max_speed_kmh",
            "avg_throttle_pct", "peak_brake_pct",
        ],
    )
    if verbose:
        print(f"  sectors    {sector_count:>7,} rows")

    telemetry_count = load_table_from_csv(
        conn,
        CLEAN_PATH,
        "telemetry",
        [
            "session_id", "lap_number", "session_time_s", "lap_time_s",
            "distance_m", "track_section", "sector", "speed_kmh",
            "throttle_pct", "brake_pressure_pct", "rpm",
            "steering_angle_deg", "battery_voltage_v", "powertrain_temp_c",
        ],
    )
    if verbose:
        print(f"  telemetry  {telemetry_count:>7,} rows")

    conn.close()
    return db_path


def run_query(sql, params=None, db_path=DB_PATH):
    """Run a SELECT and return the result as a DataFrame.

    Used by the analysis module and the notebook so SQL results arrive as
    something Pandas can work with directly.
    """
    conn = connect(db_path)
    try:
        return pd.read_sql_query(sql, conn, params=params)
    finally:
        conn.close()


def main():
    print("Building database\n")
    build_database()

    # Prove the tables are queryable and the foreign keys line up.
    print(f"\nDatabase written to {DB_PATH}")
    print(f"Size: {os.path.getsize(DB_PATH) / 1_000_000:.1f} MB")

    print("\nFastest lap per session (SQL):")
    result = run_query(
        """
        SELECT
            s.session_id,
            s.label,
            MIN(l.lap_time_s) AS best_lap_s,
            ROUND(AVG(l.lap_time_s), 2) AS avg_lap_s,
            MAX(l.max_speed_kmh) AS top_speed_kmh
        FROM laps l
        JOIN sessions s ON s.session_id = l.session_id
        GROUP BY s.session_id, s.label
        ORDER BY best_lap_s
        """
    )
    print(result.to_string(index=False))


if __name__ == "__main__":
    main()